In [1]:
import numpy as np
from Huffman_Code import HuffmanShaping, GeometricHuffmanCode
from HuffmanMatching.utils import GaussHermiteModulation, RandomWalkModulation, DiscretisedGaussianModulation
from HuffmanMatching import HuffmanTree

np.set_printoptions(precision=5, suppress=True)

In [2]:
class results:
    def __init__(self):
        self.constellation_size = []
        self.distribution = []
        self.huffman_shaping_matching = []
        self.huffman_shaping = []

In [3]:
variance = 1
start = 4
stop = 100
step = 2

data_teste = results()
for N in range(start, stop+1, step):
    data_teste.constellation_size.append(N)
    type_distribution = DiscretisedGaussianModulation(N, var = variance)
    p = type_distribution.probas
    symbols = type_distribution.alphas
    data_teste.distribution.append(p)
    half = N // 2
    huffman_shaping = HuffmanShaping(symbols[half:], p[half:], suffixes = ["0", "1"])
    #huffman_shaping = huffman_shaping.get_output_distribution()
    data_teste.huffman_shaping.append(huffman_shaping)
    huffman_shaping_matching = HuffmanTree(p, symbols)
    data_teste.huffman_shaping_matching.append(huffman_shaping_matching)

In [4]:
for i in range(len(data_teste.huffman_shaping)):
    arr1 = data_teste.huffman_shaping[i].get_output_distribution()
    arr2 = data_teste.huffman_shaping_matching[i].true_distribution
    print(f"N = {data_teste.constellation_size[i]} = {np.array_equal(arr1, arr2)}")

N = 4 = True
N = 6 = True
N = 8 = True
N = 10 = True
N = 12 = True
N = 14 = True
N = 16 = True
N = 18 = True
N = 20 = True
N = 22 = True
N = 24 = True
N = 26 = True
N = 28 = True
N = 30 = True
N = 32 = True
N = 34 = True
N = 36 = True
N = 38 = True
N = 40 = True
N = 42 = True
N = 44 = True
N = 46 = True
N = 48 = True
N = 50 = True
N = 52 = True
N = 54 = True
N = 56 = True
N = 58 = True
N = 60 = True
N = 62 = True
N = 64 = True
N = 66 = True
N = 68 = True
N = 70 = True
N = 72 = True
N = 74 = True
N = 76 = True
N = 78 = True
N = 80 = True
N = 82 = True
N = 84 = True
N = 86 = True
N = 88 = True
N = 90 = True
N = 92 = True
N = 94 = True
N = 96 = True
N = 98 = True
N = 100 = True


#### distributions testes

In [6]:
constallation_size = 3
variance = 1
gausshermite_distribution = GaussHermiteModulation(constallation_size, variance)
print(gausshermite_distribution.probas)
print(gausshermite_distribution.alphas)

[0.1666666666666666, 0.6666666666666669, 0.1666666666666666]
[-1.7320508075688774, 0.0, 1.7320508075688774]


In [7]:
bonomial_distribution = RandomWalkModulation(constallation_size, variance)
print(bonomial_distribution.probas)
print(bonomial_distribution.alphas)

[0.25 0.5  0.25]
[-1.41421  0.       1.41421]


In [8]:
gaussian_distribution = DiscretisedGaussianModulation(constallation_size)
print(gaussian_distribution.probas)
print(gaussian_distribution.alphas)

[0.03129 0.93743 0.03129]
[-3.99776  0.       3.99776]
