In [1]:
import numpy as np
from Huffman_Code import HuffmanShaping, GeometricHuffmanCode
from HuffmanMatching.utils import GaussHermiteModulation, RandomWalkModulation, DiscretisedGaussianModulation

In [2]:
class results:
    def __init__(self):
        self.constellation_size = []
        self.distribution = []
        self.huffman_shaping = []
        self.huffman_geometric = []

In [ ]:
#Qual variância usar?
variance = 1

gausshermite_results = results()
for N in range(3, 34, 3):
    gausshermite_results.constellation_size.append(N)
    gausshermite_distribution = GaussHermiteModulation(N, variance).probas
    gausshermite_results.distribution.append(gausshermite_distribution)
    symbols = list(range(N))
    huffman_shaping = HuffmanShaping(symbols, gausshermite_distribution, suffixes = ["0", "1"])
    huffman_shaping = huffman_shaping.get_output_distribution()
    #confirmar sobre o resultado do huffman shaping
    gausshermite_results.huffman_shaping.append(huffman_shaping)
    huffman_geometric = GeometricHuffmanCode(symbols, gausshermite_distribution).dyadic_distribution
    gausshermite_results.huffman_geometric.append(huffman_geometric)

In [38]:
binomial_results = results()
for N in range(3, 34, 3):
    binomial_results.constellation_size.append(N)
    bonomial_distribution = RandomWalkModulation(N, variance).probas
    binomial_results.distribution.append(gausshermite_distribution)
    symbols = list(range(N))
    huffman_shaping = HuffmanShaping(symbols, gausshermite_distribution, suffixes = ["0", "1"])
    huffman_shaping = huffman_shaping.get_output_distribution()
    binomial_results.huffman_shaping.append(huffman_shaping)
    huffman_geometric = GeometricHuffmanCode(symbols, gausshermite_distribution).dyadic_distribution
    binomial_results.huffman_geometric.append(huffman_geometric)

In [39]:
gaussian_results = results()
for N in range(3, 34, 3):
    gaussian_results.constellation_size.append(N)
    gaussian_distribution = DiscretisedGaussianModulation(N).probas
    gaussian_results.distribution.append(gausshermite_distribution)
    symbols = list(range(N))
    huffman_shaping = HuffmanShaping(symbols, gausshermite_distribution, suffixes = ["0", "1"])
    huffman_shaping = huffman_shaping.get_output_distribution()
    gaussian_results.huffman_shaping.append(huffman_shaping)
    huffman_geometric = GeometricHuffmanCode(symbols, gausshermite_distribution).dyadic_distribution
    gaussian_results.huffman_geometric.append(huffman_geometric)

#### testes

In [11]:
constallation_size = 3
variance = 1
gausshermite_distribution = GaussHermiteModulation(constallation_size, variance)
print(gausshermite_distribution.probas)
print(gausshermite_distribution.alphas)

[0.1666666666666666, 0.6666666666666669, 0.1666666666666666]
[-1.7320508075688774, 0.0, 1.7320508075688774]


In [12]:
bonomial_distribution = RandomWalkModulation(constallation_size, variance)
print(bonomial_distribution.probas)
print(bonomial_distribution.alphas)

[0.25 0.5  0.25]
[-1.41421356  0.          1.41421356]


In [13]:
gaussian_distribution = DiscretisedGaussianModulation(constallation_size)
print(gaussian_distribution.probas)
print(gaussian_distribution.alphas)

[0.0312851 0.9374298 0.0312851]
[-3.99775562  0.          3.99775562]
